name: "11_project"
type: "python:3.11"

relationships:
  database: "db:postgresql"

web:
  upstream:
    socket_family:unix
  commands:
    start: "gunicorn -w  4 -b unix:$SOCKET 11_project.wsgi.application"
  locations:
    "/":
      passthru: true
    "/static":
      root: "static"
      expires: 1h
      allow: true
disk: 512  

mounts:
  "logs":
    source: local
    source_path: logs

hooks:
  build: |
    pip install --upgrade pip
    pip install -r requirements.text
    pip install -r requirements_remote.text

  mkdir logs:
    python manage.py collectstatic
    rm -rf logs

  deploy: |
    python manage.py migrate                  